=== vikascdy/MavenJenkinsIntegrationV1/sm_test/sm/sm-docker-dist/target/bundle/ServiceManager/conf/Configuration.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="DeploymentConfiguration" type="deploymentConfiguration" />

	<xs:element name="Cluster" type="cluster" />

	<xs:element name="JVMOptions" type="jvmOptions" />

	<xs:element name="Node" type="node" />

	<xs:element name="Product" type="product" />

	<xs:element name="Property" type="property" />

	<xs:element name="Resource" type="resourceReference" />

	<xs:element name="Server" type="server" />

	<xs:element name="Service" nillable="true" type="xs:anyType" />

	<xs:complexType name="cluster">
		<xs:choice maxOccurs="unbounded">
			<xs:element name="Description" type="xs:string" minOccurs="0" />
			<xs:element name="EnvironmentType" type="xs:string"
				minOccurs="0" />
			<xs:element name="Name" type="xs:string" minOccurs="0" />

			<xs:element ref="Product" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="Resource" type="resource" minOccurs="0"
				maxOccurs="unbounded" />
			<xs:element ref="Server" minOccurs="0" maxOccurs="unbounded" />
		</xs:choice>
	</xs:complexType>

	<xs:complexType name="product">
		<xs:choice maxOccurs="unbounded">
			<xs:element name="Name" type="xs:string" minOccurs="0" />
			<xs:element name="Version" type="xs:string" minOccurs="0" />
		</xs:choice>
	</xs:complexType>

	<xs:complexType name="resource">
		<xs:choice maxOccurs="unbounded">
			<xs:element name="Description" type="xs:string" minOccurs="0" />
			<xs:element name="Name" type="xs:string" minOccurs="0" />
			<xs:element ref="Property" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="Type" type="xs:string" minOccurs="0" />
		</xs:choice>
	</xs:complexType>

	<xs:complexType name="property">
		<xs:choice maxOccurs="unbounded">
			<xs:element name="Name" type="xs:string" minOccurs="0" />
			<xs:element name="Value" type="xs:string" minOccurs="0" />
		</xs:choice>
	</xs:complexType>

	<xs:complexType name="server">
		<xs:choice maxOccurs="unbounded">
			<xs:element name="Description" type="xs:string" minOccurs="0" />
			<xs:element name="HostName" type="xs:string" minOccurs="0" />
			<xs:element name="IPAddress" type="xs:string" minOccurs="0" />
			<xs:element name="MessagePort" type="xs:int" minOccurs="0" />
			<xs:element name="Name" type="xs:string" minOccurs="0" />
			<xs:element name="LogLevel" type="logLevel" minOccurs="0" />
			<xs:element ref="Node" minOccurs="0" maxOccurs="unbounded" />
		</xs:choice>
	</xs:complexType>

	<xs:complexType name="node">
		<xs:choice maxOccurs="unbounded">
			<xs:element name="CommunicationPort" type="xs:int"
				minOccurs="0" />
			<xs:element name="Description" type="xs:string" minOccurs="0" />
			<xs:element ref="JVMOptions" minOccurs="0" />
			<xs:element name="MessagePort" type="xs:int" minOccurs="0" />
			<xs:element name="Name" type="xs:string" minOccurs="0" />
			<xs:element name="Role" type="xs:string" minOccurs="0" />
			<xs:element ref="Service" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="SSHPort" type="xs:int" minOccurs="0" />
			<xs:element name="LogLevel" type="logLevel" minOccurs="0" />
		</xs:choice>
	</xs:complexType>

	<xs:complexType name="jvmOptions">
		<xs:choice maxOccurs="unbounded">
			<xs:element ref="Property" minOccurs="0" maxOccurs="unbounded" />
		</xs:choice>
	</xs:complexType>

	<xs:complexType name="service">
		<xs:choice maxOccurs="unbounded">
			<xs:element name="Description" type="xs:string" minOccurs="0" />
			<xs:element name="LogLevel" type="logLevel" minOccurs="0" />
			<xs:element name="Name" type="xs:string" minOccurs="0" />
			<xs:element ref="Property" minOccurs="0" maxOccurs="unbounded" />
			<xs:element ref="Resource" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="ServiceType" type="xs:string" minOccurs="0" />
			<xs:element ref="Service" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="Version" type="xs:string" minOccurs="0" />
		</xs:choice>
	</xs:complexType>

	<xs:complexType name="resourceReference">
		<xs:choice maxOccurs="unbounded">
			<xs:element name="Name" type="xs:string" minOccurs="0" />
			<xs:element name="TypeName" type="xs:string" minOccurs="0" />
			<xs:element ref="Property" minOccurs="0" maxOccurs="unbounded" />
		</xs:choice>
	</xs:complexType>

	<xs:complexType name="serviceReference">
		<xs:choice maxOccurs="unbounded">
			<xs:element name="Name" type="xs:string" minOccurs="0" />
			<xs:element name="TypeName" type="xs:string" minOccurs="0" />
		</xs:choice>
	</xs:complexType>

	<xs:complexType name="dateAdapter">
		<xs:complexContent>
			<xs:extension base="xmlAdapter">
				<xs:sequence />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="xmlAdapter" abstract="true">
		<xs:sequence />
	</xs:complexType>

	<xs:complexType name="deploymentConfiguration">
		<xs:choice maxOccurs="unbounded">
			<xs:element name="CreatedDate" type="xs:string" minOccurs="0" />
			<xs:element name="Description" type="xs:string" minOccurs="0" />
			<xs:element name="Name" type="xs:string" minOccurs="0" />
			<xs:element name="Version" type="xs:string" minOccurs="0" />
			<xs:element name="MetadataVersion" type="xs:string"
				minOccurs="0" />
			<xs:element ref="Cluster" minOccurs="0" maxOccurs="unbounded" />
		</xs:choice>
	</xs:complexType>

	<xs:simpleType name="logLevel">
		<xs:restriction base="xs:string">
			<xs:enumeration value="FATAL" />
			<xs:enumeration value="DEBUG" />
			<xs:enumeration value="ERROR" />
			<xs:enumeration value="WARNING" />
			<xs:enumeration value="INFO" />
		</xs:restriction>
	</xs:simpleType>


	<xs:simpleType name="resourceType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Database" />
			<xs:enumeration value="JMSQueue" />
			<xs:enumeration value="EmailServer" />
			<xs:enumeration value="ApplicationServer" />
			<xs:enumeration value="SharedFolder" />
			<xs:enumeration value="Artifact" />
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== vikascdy/MavenJenkinsIntegrationV1/sm_test/examples/discussion-forum/discussion-forum-dist/src/dist/artifacts/Configuration.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<DeploymentConfiguration xsi:noNamespaceSchemaLocation="Configuration.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <Cluster>
        <Server>
            <Description></Description>
            <HostName>localhost</HostName>
            <IPAddress>127.0.0.1</IPAddress>
            <Node>
                <Name>discussion-forum-node-1</Name>
                <Service>
                    <Name>discussion-forum-service-1</Name>
                    <ServiceType>discussion-forum-service</ServiceType>
                    <Version>1.0.0.0</Version>
                    <Property>
                        <Name>DiscussionForum</Name>
                        <Value>Hello World!</Value>
                    </Property>
                </Service>
            </Node>
        </Server>
    </Cluster>
</DeploymentConfiguration>

=== vikascdy/MavenJenkinsIntegrationV1/sm_test/sm/sm-docker-dist/target/bundle/ServiceManager/conf/Core-Configuration.xml
<DeploymentConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="Configuration.xsd">

	<Cluster>
		<Server>
			<Node>
				<Name>Core</Name>
				<LogLevel>WARNING</LogLevel>

				<JVMOptions>
					<Property>
						<Value>-Xms1024M</Value>
					</Property>
					<Property>
						<Value>-Xmx1024M</Value>
					</Property>
				</JVMOptions>

				<!-- Spray Service -->
				<Service>
					<Name>spray-service</Name>
					<ServiceType>spray-service</ServiceType>
					<Description>Spray HTTP Service</Description>
					<LogLevel>INFO</LogLevel>
					<Version>1.0</Version>
					<Property>
						<Name>http.port</Name>
						<Value>8080</Value>
					</Property>
				</Service>

				<!-- xboard Portal Service -->
				<Service>
					<Name>xboard-portal-service</Name>
					<ServiceType>xboard-portal-service</ServiceType>
					<Description>Navigation Menu Service</Description>
					<LogLevel>DEBUG</LogLevel>
					<Version>1.0</Version>
				</Service>

				<!-- esm-service -->
				<Service>
					<Name>esm-service</Name>
					<ServiceType>esm-service</ServiceType>
					<Description>esm-service</Description>
					<LogLevel>WARNING</LogLevel>
					<Version>1.0</Version>
					<Property>
						<Name>password.max.attempts</Name>
						<Value>5</Value>
					</Property>
					<Property>
						<Name>password.reset.lockout.interval</Name>
						<Value>5</Value>
					</Property>
					<Property>
						<Name>password.reset.login</Name>
						<Value>false</Value>
					</Property>
					<Property>
						<Name>password.lockout.duration</Name>
						<Value>15</Value>
					</Property>
					<Property>
						<Name>password.history</Name>
						<Value>3</Value>
					</Property>
					<Property>
						<Name>password.age</Name>
						<Value>120</Value>
					</Property>
					<Property>
						<Name>password.regex</Name>
						<Value>^([a-zA-Z0-9@*#]{8,15})$</Value>
					</Property>
                    <Property>
                        <Name>password.regex.name</Name>
                        <Value>Default Password Regex</Value>
                    </Property>
					<Property>
						<Name>password.regex.description</Name>
						<Value>Password matching expression. Match all alphanumeric character and predefined wild characters. Password must consists of at least 8 characters and not more than 15 characters</Value>
					</Property>
					<Resource>
						<Name>Persisted H2 DB</Name>
						<TypeName>Security Database</TypeName>
					</Resource>
				</Service>

				<!-- Content Repository -->
				<Service>
					<Name>content-repository-service</Name>
					<ServiceType>content-repository-service</ServiceType>
					<Description>Content Repository Service</Description>
					<LogLevel>WARNING</LogLevel>
					<Version>1.0</Version>
				</Service>

                <!-- Flex Fields Service -->
                <Service>
                    <Name>flexfields-service</Name>
                    <ServiceType>flexfields-service</ServiceType>
                    <Description>flexfields-service</Description>
                    <LogLevel>WARNING</LogLevel>
                    <Version>1.0.0.0</Version>
                    <Resource>
                        <Name>FlexField Database</Name>
                        <TypeName>FlexField Database</TypeName>
                    </Resource>
                </Service>
			</Node>
		</Server>
		<Resource>
			<Description></Description>
			<Name>In Memory H2 DB</Name>
			<Property>
				<Name>URL</Name>
				<Value>jdbc:h2:mem:securityDB</Value>
			</Property>
			<Property>
				<Name>Driver</Name>
				<Value>org.h2.Driver</Value>
			</Property>
			<Property>
				<Name>Dialect</Name>
				<Value>org.hibernate.dialect.H2Dialect</Value>
			</Property>
			<Property>
				<Name>Username</Name>
				<Value>sa</Value>
			</Property>
			<Property>
				<Name>Password</Name>
				<Value></Value>
			</Property>
			<Property>
				<Name>AutoCreate</Name>
				<Value>true</Value>
			</Property>
			<Type>JDBC Database</Type>
		</Resource>
		<Resource>
			<Description></Description>
			<Name>Persisted H2 DB</Name>
			<Property>
				<Name>URL</Name>
				<Value>jdbc:h2:file:securityDB</Value>
			</Property>
			<Property>
				<Name>Driver</Name>
				<Value>org.h2.Driver</Value>
			</Property>
			<Property>
				<Name>Dialect</Name>
				<Value>org.hibernate.dialect.H2Dialect</Value>
			</Property>
			<Property>
				<Name>Username</Name>
				<Value>sa</Value>
			</Property>
			<Property>
				<Name>Password</Name>
				<Value></Value>
			</Property>
			<Property>
				<Name>AutoCreate</Name>
				<Value>true</Value>
			</Property>
			<Type>JDBC Database</Type>
		</Resource>
        <!-- FlexField DB -->
        <Resource>
            <Description></Description>
            <Name>FlexField Database</Name>
            <Property>
                <Name>URL</Name>
                <Value>jdbc:h2:file:FlexFieldDB</Value>
            </Property>
            <Property>
                <Name>Driver</Name>
                <Value>org.h2.Driver</Value>
            </Property>
            <Property>
                <Name>Dialect</Name>
                <Value>org.hibernate.dialect.H2Dialect</Value>
            </Property>
            <Property>
                <Name>Username</Name>
                <Value>sa</Value>
            </Property>
            <Property>
                <Name>Password</Name>
                <Value></Value>
            </Property>
            <Property>
                <Name>AutoCreate</Name>
                <Value>true</Value>
            </Property>
            <Type>JDBC Database</Type>
        </Resource>

        <Resource>
            <Description></Description>
            <Name>FlexFields Persisted MySQL</Name>
            <Property>
                <Name>URL</Name>
                <Value>jdbc:mysql://smbox:3306/flexfields</Value>
            </Property>
            <Property>
                <Name>Driver</Name>
                <Value>com.mysql.jdbc.Driver</Value>
            </Property>
            <Property>
                <Name>Dialect</Name>
                <Value>org.hibernate.dialect.MySQLDialect</Value>
            </Property>
            <Property>
                <Name>Username</Name>
                <Value>sm</Value>
            </Property>
            <Property>
                <Name>Password</Name>
                <Value>welcome</Value>
            </Property>
            <Property>
                <Name>AutoCreate</Name>
                <Value>true</Value>
            </Property>
            <Type>JDBC Database</Type>
        </Resource>

	</Cluster>
</DeploymentConfiguration>

=== vikascdy/MavenJenkinsIntegrationV1/sm_test/examples/hello-example/hello-example-dist/target/bundle/artifacts/Configuration.xml
<DeploymentConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                         xsi:noNamespaceSchemaLocation="Configuration.xsd">

    <Cluster>
        <Server>
            <Name>default</Name>
            <IPAddress>127.0.0.1</IPAddress>
            <HostName>localhost</HostName>
            <Node>
                <Name>HelloExampleNode</Name>

                <Service>
                    <Name>hello-example-service-1</Name>
                    <ServiceType>hello-example-service</ServiceType>
                    <Version>1.0.0.0</Version>
                    <Property>
                        <Name>name</Name>
                        <Value>John Smith</Value>
                    </Property>
                </Service>
            </Node>
        </Server>
    </Cluster>

</DeploymentConfiguration>

=== vikascdy/MavenJenkinsIntegrationV1/sm_test/examples/discussion-forum/discussion-forum-launcher/src/main/resources/conf/Configuration.xml
<DeploymentConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="Configuration.xsd">

	<CreatedDate>2014-07-19</CreatedDate>
	<Version>0.0.1</Version>
	<MetadataVersion>0.0.1</MetadataVersion>
	<Name>Main Configuration</Name>
	<Description>Development Deployment Configuration</Description>

	<Cluster>
		<Name>DevelopmentCluster</Name>
		<EnvironmentType>TEST</EnvironmentType>
		<Server>
			<Name>default</Name>
			<IPAddress>127.0.0.1</IPAddress>
			<HostName>localhost</HostName>

			<Node>
				<Name>DF</Name>

				<JVMOptions>
					<Property>
						<Value>-Xms1024M</Value>
					</Property>
					<Property>
						<Value>-Xmx1024M</Value>
					</Property>
				</JVMOptions>

				<Service>
                    <!-- Unique identifiable name for this instance of the service in the cluster -->
                    <Name>Discussion Forum Service 1</Name>

                    <!-- Service type and version identifies in the MANIFEST.yaml file and the service annotations -->
                    <ServiceType>discussion-forum-service</ServiceType>
                    <Version>1.0</Version>


                    <Description>This is a sample configuration of the Discussion Forum Service</Description>

                    <!-- The values of the property configurations defined for the service -->
                    <Property>
                        <Name>name</Name>
                        <Value>Bob</Value>
                    </Property>

                </Service>

			</Node>
		</Server>
	</Cluster>
</DeploymentConfiguration>
